Requiring 'rom/sql' to avoid errors in rake tasks
The error was:

    NameError: uninitialized constant ROM
    /PATH_TO_PROJECT/sinatra-rom/Rakefile:7:in `block (2 levels) in
    <top (required)>'
    Tasks: TOP => db:create_migration => db:load_setup